Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.s3.bucket}
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html