export const ActionTypes = {
  GET_VIDEOS_FAILURE: 'videos/GET_VIDEOS_FAILURE',
  GET_VIDEOS_REQUEST: 'videos/GET_VIDEOS_REQUEST',
  GET_VIDEOS_SUCCESS: 'videos/GET_VIDEOS_SUCCESS',
  SELECT_NEXT_VIDEO: 'videos/SELECT_NEXT_VIDEO',
  SELECT_PREV_VIDEO: 'videos/SELECT_PREV_VIDEO',
  SELECT_VIDEO: 'videos/SELECT_VIDEO'
};