export const ActionTypes = {
  GET_CHANNELS_FAILURE: 'channels/GET_CHANNELS_FAILURE',
  GET_CHANNELS_REQUEST: 'channels/GET_CHANNELS_REQUEST',
  GET_CHANNELS_SUCCESS: 'channels/GET_CHANNELS_SUCCESS',
  SELECT_CHANNEL: 'channels/SELECT_CHANNEL'
};