service: soulprovidr-tv-api

# Define variables.
custom:
  dynamodb:
    channelsTable: channels
    videosTable: videos
  s3:
    bucket: soulprovidr.tv

provider:
  name: aws
  runtime: nodejs8.10
  versionFunctions: false
  profile: soulprovidr
  region: ca-central-1
  stage: dev
  environment:
    CHANNELS_TABLE: ${self:custom.dynamodb.channelsTable}
    S3_BUCKET: ${self:custom.s3.bucket}
    VIDEOS_TABLE: ${self:custom.dynamodb.videosTable}

  # Allow Lambda all permissions for S3 bucket and DB tables.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::${self:custom.s3.bucket}/*"

    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/*"

functions:
  - ${file(./handlers/channels/functions.yml)}
  - ${file(./handlers/videos/functions.yml)}

resources:
  - ${file(./resources/dynamodb.yml)}
  - ${file(./resources/s3.yml)}