service: api

# Define variables.
custom:
  dynamodb:
    channelsTable: channels
    videosTable: videos
  s3:
    bucket: soulprovidr.tv

provider:
  name: aws
  runtime: nodejs8.10
  versionFunctions: false
  profile: soulprovidr
  region: ca-central-1
  stage: dev
  environment:
    CHANNELS_TABLE: ${self:custom.dynamodb.channelsTable}
    S3_BUCKET: ${self:custom.s3.bucket}
    VIDEOS_TABLE: ${self:custom.dynamodb.videosTable}

  # Allow Lambda all permissions for S3 bucket and DB tables.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::${self:custom.s3.bucket}/*"

    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/*"

functions:
  # getChannels:
  #   handler: handler.getChannels
  #   description: Retrieve the list of channels.

  # saveChannel:
  #   handler: handler.saveChannel
  #   description: Create or update a channel.

  saveVideo:
    handler: index.saveVideo
    description: Saves the specified YouTube video to the S3 bucket.

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3.bucket}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html

    VideosTable:
      Type: AWS::DynamoDB::Table
      # DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.dynamodb.videosTable}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    ChannelsTable:
      Type: AWS::DynamoDB::Table
      # DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.dynamodb.channelsTable}
        AttributeDefinitions:
          - AttributeName: slug
            AttributeType: S
        KeySchema:
          - AttributeName: slug
            KeyType: HASH
        ProvisionedThroughput:
          ReactCapacityUnits: 1
          WriteCapacityUnits: 1