channels-list:
    handler: modules/channels.list
    events:
      - http:
          path: channels
          method: get
          cors: true

channels-save:
  handler: modules/channels.save

videos-list:
  handler: modules/videos.list
  events:
    - http:
        path: videos
        method: get
        cors: true

videos-save:
  handler: modules/videos.save
  reservedConcurrency: 10
  timeout: 30
  events:
    # Save videos as they are pushed into the queue.
    - sqs:
        arn: arn:aws:sqs:${self:provider.region}:#{AWS::AccountId}:${self:custom.videos.queueName}
        batchSize: 1